# Generated by Django 5.2 on 2025-04-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='notes',
        ),
    ]
